// lib/algorithms/response_engine.dart
import '../models/document_model.dart';
import 'package:intl/intl.dart';

enum ResponseType {
  formalLetter, report, email, actionPlan,
  executiveSummary, acknowledgement, inquiry, rejection,
}

class ResponseEngine {
  static String generate({
    required DocAnalysis analysis,
    required ResponseType type,
    required String userInstructions,
    String senderName    = 'Your Name',
    String senderTitle   = 'Your Title',
    String recipientName = 'Recipient',
    String subject       = '',
  }) {
    final date = DateFormat('MMMM d, yyyy').format(DateTime.now());
    final resolvedSubject = subject.isNotEmpty ? subject : 'Re: ${analysis.docCategory}';
    switch (type) {
      case ResponseType.formalLetter:
        return _formalLetter(analysis, userInstructions, date, senderName, senderTitle, recipientName, resolvedSubject);
      case ResponseType.report:
        return _report(analysis, userInstructions, date, resolvedSubject);
      case ResponseType.email:
        return _email(analysis, userInstructions, date, senderName, recipientName, resolvedSubject);
      case ResponseType.actionPlan:
        return _actionPlan(analysis, userInstructions, date, resolvedSubject);
      case ResponseType.executiveSummary:
        return _executiveSummary(analysis, userInstructions, date, resolvedSubject);
      case ResponseType.acknowledgement:
        return _acknowledgement(analysis, userInstructions, date, senderName, recipientName, resolvedSubject);
      case ResponseType.inquiry:
        return _inquiry(analysis, userInstructions, date, senderName, recipientName, resolvedSubject);
      case ResponseType.rejection:
        return _rejection(analysis, userInstructions, date, senderName, recipientName, resolvedSubject);
    }
  }

  static String _formalLetter(DocAnalysis a, String inst, String date,
      String sender, String title, String recipient, String subject) => '''
$sender
$title
$date

$recipient

Subject: $subject

Dear $recipient,

I am writing with reference to the ${a.docCategory.toLowerCase()} that has been brought to our attention. Having carefully reviewed the document, I would like to provide the following response.

${_instPara(inst)}

Upon thorough review, the key matters identified are as follows:

${_bullets(a.keyPoints.take(4).toList())}

${_closing(inst)}

The central finding of the document: "${a.mainMessage}"

Should you require any further information, please do not hesitate to contact me.

Yours sincerely,
$sender
$title
''';

  static String _report(DocAnalysis a, String inst, String date, String subject) => '''
PROFESSIONAL REPORT
$subject
Date: $date  |  Document Type: ${a.docCategory}
${'-' * 60}

1. EXECUTIVE OVERVIEW
${a.shortSummary}

${_instPara(inst)}

2. DETAILED ANALYSIS
${a.fullSummary}

3. KEY FINDINGS
${_numbered(a.keyPoints)}

4. CRITICAL HIGHLIGHTS
${_bullets(a.highlights)}

5. KEYWORDS & THEMES
${a.keywords.join(', ')}

6. DOCUMENT METRICS
  Word Count:        ${a.wordCount}
  Reading Time:      ${a.readTime}
  Document Type:     ${a.docCategory}
  Readability Score: ${a.readabilityScore.toStringAsFixed(1)} / 100

7. CONCLUSION
${a.mainMessage}

${_closing(inst)}
${'-' * 60}
Generated by DocuAI — $date
''';

  static String _email(DocAnalysis a, String inst, String date,
      String sender, String recipient, String subject) => '''
Subject: $subject
Date: $date  |  To: $recipient  |  From: $sender

Dear $recipient,

I hope this email finds you well.

${_instPara(inst)}

After reviewing the ${a.docCategory.toLowerCase()}, here is a brief summary:

${_bullets(a.keyPoints.take(3).toList())}

In essence: "${a.mainMessage}"

${_closing(inst)}

Best regards,
$sender
''';

  static String _actionPlan(DocAnalysis a, String inst, String date, String subject) => '''
ACTION PLAN
$subject
Prepared: $date
${'-' * 60}

BACKGROUND
${a.shortSummary}

${_instPara(inst)}

REQUIRED ACTIONS
${_actionItems(a.keyPoints)}

PRIORITY HIGHLIGHTS
${_bullets(a.highlights)}

KEY THEMES
${a.keywords.take(6).map((k) => '  -> $k').join('\n')}

CORE MESSAGE TO RESOLVE
"${a.mainMessage}"

${_closing(inst)}
${'-' * 60}
DocuAI | $date
''';

  static String _executiveSummary(DocAnalysis a, String inst, String date, String subject) => '''
EXECUTIVE SUMMARY
$subject  |  $date
${'-' * 60}

PURPOSE
${_instPara(inst)}

SUMMARY
${a.fullSummary}

KEY POINTS
${_numbered(a.keyPoints)}

CRITICAL STATEMENT
"${a.mainMessage}"

DOCUMENT PROFILE
  Category:    ${a.docCategory}
  Word Count:  ${a.wordCount}
  Read Time:   ${a.readTime}
  Themes:      ${a.keywords.take(5).join(', ')}

CONCLUSION
This ${a.docCategory.toLowerCase()} presents information of significance. The highlighted points represent the core message and should inform any decisions taken in response.

${'-' * 60}
DocuAI | $date
''';

  static String _acknowledgement(DocAnalysis a, String inst, String date,
      String sender, String recipient, String subject) => '''
$sender
$date

$recipient

Subject: Acknowledgement — $subject

Dear $recipient,

I am writing to acknowledge receipt of the ${a.docCategory.toLowerCase()}.

${_instPara(inst)}

We confirm receipt and review of the document. The following key points have been noted:

${_bullets(a.keyPoints.take(3).toList())}

We will review all details and revert with a comprehensive response. Should you require urgent clarification, please feel free to reach out.

Thank you for bringing this matter to our attention.

Yours faithfully,
$sender
''';

  static String _inquiry(DocAnalysis a, String inst, String date,
      String sender, String recipient, String subject) => '''
$sender
$date

$recipient

Subject: Inquiry Regarding — $subject

Dear $recipient,

I am writing to seek clarification on certain aspects of the ${a.docCategory.toLowerCase()} provided.

${_instPara(inst)}

Upon reviewing the document, several points require elaboration:

${_questions(a.keyPoints.take(4).toList())}

The document states: "${a.mainMessage}" — we would appreciate further detail on this.

Your prompt response would be greatly appreciated.

Respectfully,
$sender
''';

  static String _rejection(DocAnalysis a, String inst, String date,
      String sender, String recipient, String subject) => '''
$sender
$date

$recipient

Subject: Response to — $subject

Dear $recipient,

Thank you for submitting the ${a.docCategory.toLowerCase()} for our consideration.

${_instPara(inst)}

After careful review, we regret to inform you that we are unable to proceed as proposed at this time.

Our review noted the following:

${_bullets(a.keyPoints.take(3).toList())}

We remain open to future opportunities and encourage you to consider revising the proposal taking into account the points highlighted above.

Yours sincerely,
$sender
''';

  // ── Helpers ────────────────────────────────────────────────────────────────
  static String _instPara(String i) {
    if (i.trim().isEmpty) return '';
    final s = i.trim();
    return '${s[0].toUpperCase()}${s.substring(1)}\n';
  }

  static String _closing(String i) {
    if (i.toLowerCase().contains('urgent')) {
      return 'Given the urgent nature, we request your prompt attention at the earliest.';
    }
    return 'We look forward to your response and remain available for further discussion.';
  }

  static String _bullets(List<String> items) =>
      items.map((i) => '  • ${i.trim()}').join('\n');

  static String _numbered(List<String> items) =>
      items.asMap().entries.map((e) => '  ${e.key + 1}. ${e.value.trim()}').join('\n');

  static String _actionItems(List<String> items) =>
      items.asMap().entries.map((e) =>
        '  ACTION ${e.key + 1}: ${e.value.trim()}\n  Status: [ ] Pending    Due: ___________\n'
      ).join('\n');

  static String _questions(List<String> items) =>
      items.asMap().entries.map((e) =>
        '  Q${e.key + 1}: Could you elaborate on — "${e.value.trim()}"?'
      ).join('\n');
}
