// lib/services/pdf_export_service.dart
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../models/document_model.dart';

class PdfExportService {
  // ── Export analysis summary as PDF ────────────────────────────────────────
  static Future<String> exportSummary({
    required DocAnalysis analysis,
    required String originalFileName,
  }) async {
    final doc  = pw.Document();
    final date = DateFormat('MMMM d, yyyy').format(DateTime.now());

    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      header: (_) => _header('Document Analysis Report', date),
      footer: (ctx) => _footer(ctx),
      build: (_) => [
        pw.SizedBox(height: 12),
        pw.Text('Source: $originalFileName',
            style: pw.TextStyle(fontSize: 11, color: PdfColors.blueGrey600,
                fontStyle: pw.FontStyle.italic)),
        pw.SizedBox(height: 4),
        pw.Text(
          '${analysis.docCategory}  •  ${analysis.wordCount} words  •  ${analysis.readTime}  •  Readability: ${analysis.readabilityScore.toStringAsFixed(0)}/100',
          style: pw.TextStyle(fontSize: 9, color: PdfColors.blueGrey400),
        ),
        pw.SizedBox(height: 20),
        pw.Divider(color: PdfColors.blueGrey300),
        pw.SizedBox(height: 14),
        _section('Main Message', analysis.mainMessage, highlight: true),
        pw.SizedBox(height: 14),
        _section('Summary', analysis.fullSummary),
        pw.SizedBox(height: 14),
        _bulletSection('Key Points', analysis.keyPoints),
        pw.SizedBox(height: 14),
        _bulletSection('Critical Highlights', analysis.highlights,
            color: PdfColors.amber800),
        pw.SizedBox(height: 14),
        _section('Keywords', analysis.keywords.join('  •  ')),
      ],
    ));

    return _save(doc, 'Summary');
  }

  // ── Export response document as PDF ──────────────────────────────────────
  static Future<String> exportResponse({
    required String content,
    required String title,
  }) async {
    final doc  = pw.Document();
    final date = DateFormat('MMMM d, yyyy').format(DateTime.now());

    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(42),
      header: (_) => _header(title, date),
      footer: (ctx) => _footer(ctx),
      build: (_) => [
        pw.SizedBox(height: 16),
        ..._parseContent(content),
      ],
    ));

    return _save(doc, title.replaceAll(' ', '_'));
  }

  // ── Internal helpers ──────────────────────────────────────────────────────
  static pw.Widget _header(String title, String date) => pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Text('DocuAI', style: pw.TextStyle(
            fontSize: 20, fontWeight: pw.FontWeight.bold,
            color: PdfColors.blue800)),
        pw.Text(date, style: pw.TextStyle(
            fontSize: 9, color: PdfColors.blueGrey500)),
      ]),
      pw.SizedBox(height: 6),
      pw.Text(title, style: pw.TextStyle(
          fontSize: 16, fontWeight: pw.FontWeight.bold,
          color: PdfColors.blueGrey800)),
      pw.SizedBox(height: 6),
      pw.Container(height: 2, color: PdfColors.blue700),
    ],
  );

  static pw.Widget _footer(pw.Context ctx) => pw.Row(
    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
    children: [
      pw.Text('Generated by DocuAI — AI Document Intelligence',
          style: pw.TextStyle(fontSize: 8, color: PdfColors.blueGrey400)),
      pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
          style: pw.TextStyle(fontSize: 8, color: PdfColors.blueGrey400)),
    ],
  );

  static pw.Widget _section(String title, String body,
      {bool highlight = false}) => pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(title, style: pw.TextStyle(
          fontSize: 12, fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue800)),
      pw.SizedBox(height: 6),
      highlight
          ? pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                color: PdfColors.amber50,
                borderRadius: pw.BorderRadius.circular(6),
                border: pw.Border.all(color: PdfColors.amber300),
              ),
              child: pw.Text(body, style: pw.TextStyle(
                  fontSize: 11, fontWeight: pw.FontWeight.bold,
                  lineSpacing: 2)))
          : pw.Text(body, style: pw.TextStyle(
              fontSize: 10, color: PdfColors.blueGrey700, lineSpacing: 2)),
    ],
  );

  static pw.Widget _bulletSection(String title, List<String> items,
      {PdfColor color = PdfColors.blue700}) => pw.Column(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Text(title, style: pw.TextStyle(
          fontSize: 12, fontWeight: pw.FontWeight.bold,
          color: PdfColors.blue800)),
      pw.SizedBox(height: 8),
      ...items.map((item) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 5),
        child: pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Container(width: 5, height: 5,
              margin: const pw.EdgeInsets.only(top: 4, right: 8),
              decoration: pw.BoxDecoration(color: color, shape: pw.BoxShape.circle)),
          pw.Expanded(child: pw.Text(item,
              style: pw.TextStyle(fontSize: 10,
                  color: PdfColors.blueGrey700, lineSpacing: 2))),
        ]),
      )),
    ],
  );

  static List<pw.Widget> _parseContent(String content) {
    final widgets = <pw.Widget>[];
    for (final para in content.split('\n\n')) {
      if (para.trim().isEmpty) continue;
      final isHeading = para.trim().length < 80 &&
          (para.trim() == para.trim().toUpperCase() ||
           para.trim().endsWith(':'));
      widgets.add(pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 10),
        child: pw.Text(para.trim(), style: pw.TextStyle(
          fontSize: isHeading ? 12 : 10,
          fontWeight: isHeading ? pw.FontWeight.bold : pw.FontWeight.normal,
          color: isHeading ? PdfColors.blueGrey900 : PdfColors.blueGrey700,
          lineSpacing: 2,
        )),
      ));
    }
    return widgets;
  }

  static Future<String> _save(pw.Document doc, String label) async {
    final dir  = await getApplicationDocumentsDirectory();
    final name = 'DocuAI_${label}_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${dir.path}/$name');
    await file.writeAsBytes(await doc.save());
    return file.path;
  }
}
